main : linked_list.o person.o main.o
    gcc -o main linked_list.o person.o main.o

linked_list.o : linked_list.c linked_list.h
    gcc -c linked_list.c

person.o : person.h person.c
    gcc -c person.c

main.o : main.c person.c person.h linked_list.h linked_list.c
    gcc -c main.c
